author: MobiLab Solutions GmbH
author_url: https://mobilabsolutions.com
github_url: https://github.com/mobilabsolutions/payment-sdk-ios-open
copyright: Copyright MobiLab Solutions GmbH 2019
hide_documentation_coverage: true
theme: fullwidth