language: objective-c
osx_image: xcode10.1

script:
  - set -e
  - echo "Starting Unit Tests"
  - travis_retry xcodebuild clean test -quiet -project MobilabPayment.xcodeproj -scheme "MobilabPaymentCore" -destination "OS=12.1,name=iPhone X" test
  - echo "Starting UI Tests"
  - travis_retry xcodebuild test -quiet -project MobilabPayment.xcodeproj -scheme "Demo" -destination "OS=12.1,name=iPhone X" test