language: objective-c
osx_image: xcode10.1

script:
  - set -o pipefail
  - xcodebuild clean test -project MobilabPayment.xcodeproj -scheme "MobilabPaymentCore" -destination "OS=12.1,name=iPhone X" test