language: objective-c
osx_image: xcode10.2

cache:
  directories:
  - Carthage
  - bundler

env:
  #environment variables
  global:
    - PROJECT_NAME="MobilabPayment.xcodeproj"
  matrix:
    - DESTINATION="OS=12.2,name=iPhone X"

before_install:
  - gem install xcpretty
  - gem install xcpretty-travis-formatter
  - bundle install
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage

before_script:
  - carthage update --cache-builds --platform iOS

script:
  - set -e
  - set -o pipefail
  - bundle exec fastlane test
  - bundle exec fastlane beta
  - echo "Building Objective-C Sample"
  - xcodebuild -project "$PROJECT_NAME" -scheme "Sample-ObjC" -destination "$DESTINATION" | xcpretty -f `xcpretty-travis-formatter`
  - echo "Building Demo application"
  - xcodebuild -project "$PROJECT_NAME" -scheme "Demo" -destination "$DESTINATION" | xcpretty -f `xcpretty-travis-formatter`
