language: objective-c
osx_image: xcode10.2

cache:
  directories:
  - Carthage

env:
  #environment variables
  global:
    - PROJECT_NAME="MobilabPayment.xcodeproj"
  matrix:
    - DESTINATION="OS=12.2,name=iPhone X"

before_install:
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage

before_script:
  - carthage update --cache-builds --platform iOS

script:
  - set -e
  - echo "Starting Unit Tests"
  - travis_retry xcodebuild clean test -quiet -project "$PROJECT_NAME" -scheme "MobilabPaymentCore" -destination "$DESTINATION" test
  - echo "Starting UI Tests"
  - xcodebuild test -project "$PROJECT_NAME" -scheme "Sample" -destination "$DESTINATION" test
  - echo "Building Objective-C Sample"
  - xcodebuild -quiet -project "$PROJECT_NAME" -scheme "Sample-ObjC" -destination "$DESTINATION" 
  - echo "Building Demo application"
  - xcodebuild -quiet -project "$PROJECT_NAME" -scheme "Demo" -destination "$DESTINATION" 
