language: objective-c
osx_image: xcode10.2

cache:
  bundler: true
  directories:
  - Carthage
  
env:
  global:
    - WORKSPACE_NAME="Stash.xcworkspace"
    - DESTINATION="OS=12.2,name=iPhone X"

install:
- gem install xcpretty
- gem install xcpretty-travis-formatter
- bundle install
- brew install carthage || true
- brew outdated carthage || brew upgrade carthage
- rm -rf Carthage
- carthage bootstrap --no-use-binaries --platform iOS --cache-builds

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: bash .travis/travis-build.sh
      env:
        - TEST_SUITE=unit
    - # stage name not required, will continue to use `test`
      script: bash .travis/travis-build.sh
      name: "UI Tests"
      env: 
        - TEST_SUITE=ui
    - stage: swiftformat
      if: branch != master AND type != pull_request
      script: bash .travis/travis-swift-format.sh
    - stage: deploy
      script: echo "Starting with beta deployment"
      if: branch = master AND type != pull_request
      deploy: 
        provider: script
        skip_cleanup: true
        script: bash .travis/travis-deploy.sh
        on:
          branch: 
            master