language: objective-c
osx_image: xcode10.2

cache:
  bundler: true
  directories:
  - Carthage

env:
  #environment variables
  global:
    - WORKSPACE_NAME="MobilabPayment.xcworkspace"
  matrix:
    - DESTINATION="OS=12.2,name=iPhone X"

install:
  - gem install xcpretty
  - gem install xcpretty-travis-formatter
  - bundle install
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --no-use-binaries --platform iOS --cache-builds

script:
  - ./travis-build.sh
